model: rcan_small
scale: 4
model_params:
  in_channels: 3
  out_channels: 3
  num_features: 64
  num_resgroups: 3
  num_resblocks: 5
  reduction: 16
data:
  test_hr: data_experiments/bsds500/HR_gray
  test_lr: data_experiments/bsds500/LR_x4_gray
eval:
  save_dir: results/generalization/bsds500_gray/rcan_small_x4
  compare_dir: results/generalization/bsds500_gray/comparisons
  crop_border: 4
  test_y_channel: true
train:
  save_dir: checkpoints/rcan_small_x4
